import type { Metadata } from "next";
import "./globals.css";
// import Nav from "@/components/nav";
import Header from "@/components/header";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-[url('/images/background-portfolio.jpg')] bg-cover bg-center min-h-screen">
        <Header />
        <div className="flex flex-1 justify-between">
          <main className="flex-1 p-6">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
