import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
// import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <aside className="w-64 bg-gray-900 text-white p-6 min-h-screen">
        <Nav />
      </aside>
      <body>
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <Nav /> */}
        <main>{children}</main>
      </div>
      </body>
    </html>
  );
}
